In [16]:
import pandas as pd

In [17]:
df_desastre = pd.read_csv('dataframes/REPORTE__DE_EVENTOS_POR_DESASTRES_NATURALES_Y_ANTR_PICOS.csv', delimiter = ',')
df_desastre

,ITEM,FECHA,EVENTO,MUNICIPIO,Familias Damnificadas/ Afectadas,Viviendas Destruidas,Viviendas Averiadas,Acueducto destruidos,Vias Destruidas,Puentes Obstruidos,Establecimientos Educativos,Afectacion Cultivos Has,Alertas,Albergues,Desaparecidos,Fallecidos,OBSERVACIONES
0,1,01/02/2023 12:00:00 AM,MOVIMIENTO EN MASA,LEBRIJA,0,0,0,0,1,0,0,0,NaN,NaN,0,0,El administrados vial Ruta del cacao reporta d...
1,2,01/02/2023 12:00:00 AM,MOVIMIENTO EN MASA,FLORIDABLANCA,0,0,0,0,1,0,0,0,NaN,NaN,0,0,El administrador vial Autovia Bucaramanga – Pa...
2,3,01/25/2023 12:00:00 AM,HELADAS,TONA,0,0,0,0,0,0,0,25,NaN,NaN,0,0,El CMGRD reporta bajas temperaturas en el corr...
3,4,01/25/2023 12:00:00 AM,HELADAS,CERRITO,0,0,0,0,0,0,0,20,NaN,NaN,0,0,El CMGRD reporta bajas temperaturas en las ver...
4,5,01/28/2023 12:00:00 AM,INCENDIO FORESTAL,EL PLAYON,0,0,0,0,0,0,0,10,NaN,NaN,0,0,El CMGRD reporta la atención de un incendio fo...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,98,07/13/2023 12:00:00 AM,INCENDIO FORESTAL,PIEDECUESTA,0,0,0,0,0,0,0,8,NaN,NaN,0,0,El comandante de bomberos reporta atención de ...
98,99,07/17/2023 12:00:00 AM,EROSION,PUERTO WILCHES,0,0,0,0,0,0,0,0,NaN,NaN,0,0,El alcalde municipal informa que el municipio ...
99,100,07/19/2023 12:00:00 AM,INCENDIO FORESTAL,EL HATO,0,0,0,0,0,0,0,10,NaN,NaN,0,0,El CMGRD reporta atención de incendio forestal...
100,101,07/22/2023 12:00:00 AM,TORMENTAS ELECTRICAS,EL CARMEN DE CHUCURI,10,0,10,0,0,0,0,0,NaN,NaN,0,0,El CMGRD reporta lluvias y fuertes vientos en ...
101,102,07/25/2023 12:00:00 AM,TORMENTAS ELECTRICAS,OCAMONTE,10,0,10,0,1,0,0,0,NaN,NaN,0,0,reportan del municipio Ocamonte sector: vereda...

Se puede buscar dentro del dataframe o filtrar por filas y columnas

In [18]:
df_desastre[5:9]

,ITEM,FECHA,EVENTO,MUNICIPIO,Familias Damnificadas/ Afectadas,Viviendas Destruidas,Viviendas Averiadas,Acueducto destruidos,Vias Destruidas,Puentes Obstruidos,Establecimientos Educativos,Afectacion Cultivos Has,Alertas,Albergues,Desaparecidos,Fallecidos,OBSERVACIONES
5,6,01/28/2023 12:00:00 AM,INCENDIO FORESTAL,CURITI,0,0,0,0,0,0,0,5,NaN,NaN,0,0,El CMGRD reporta la atención de un incendio fo...
6,7,01/29/2023 12:00:00 AM,INCENDIO FORESTAL,GUEPSA,0,0,0,0,0,0,0,2,NaN,NaN,0,0,El CMGRD reporta la atención de un incendio fo...
7,8,01/31/2023 12:00:00 AM,INCENDIO FORESTAL,CERRITO,0,0,0,0,0,0,0,10,NaN,NaN,0,0,El comandante de bomberos reporta la atención ...
8,9,01/31/2023 12:00:00 AM,INCENDIO FORESTAL,CONTRATACION,0,0,0,0,0,0,0,2,NaN,NaN,0,0,El CMGRD reporta la atención y control de un i...

In [19]:
df_desastre[['MUNICIPIO', 'Fallecidos', 'Familias Damnificadas/ Afectadas']]

                MUNICIPIO  Fallecidos  Familias Damnificadas/ Afectadas
0                 LEBRIJA           0                                 0
1           FLORIDABLANCA           0                                 0
2                    TONA           0                                 0
3                 CERRITO           0                                 0
4               EL PLAYON           0                                 0
..                    ...         ...                               ...
97            PIEDECUESTA           0                                 0
98         PUERTO WILCHES           0                                 0
99                EL HATO           0                                 0
100  EL CARMEN DE CHUCURI           0                                10
101              OCAMONTE           0                                10

[102 rows x 3 columns]

## loc e iloc, a diferencia del slicing convencional, SÍ son incluyentes con el start y el end

df.loc[a:b, ['label_1','label_2']] es un slicing más avanzado, muestra todas las filas desde a hasta b y filtra las columnas

In [20]:
df_desastre.loc[1:4, ['MUNICIPIO', 'Fallecidos', 'Familias Damnificadas/ Afectadas']]

       MUNICIPIO  Fallecidos  Familias Damnificadas/ Afectadas
1  FLORIDABLANCA           0                                 0
2           TONA           0                                 0
3        CERRITO           0                                 0
4      EL PLAYON           0                                 0

Puedo afectar los resultados filtrados con df.loc mediante operaciones

In [22]:
df_desastre.loc[:, ['Fallecidos']] + 100

     Fallecidos
0           100
1           100
2           100
3           100
4           100
..          ...
97          100
98          100
99          100
100         100
101         100

[102 rows x 1 columns]

In [24]:
df_desastre.loc[:, ['MUNICIPIO']] == 'FLORIDABLANCA'

     MUNICIPIO
0        False
1         True
2        False
3        False
4        False
..         ...
97       False
98       False
99       False
100      False
101      False

[102 rows x 1 columns]

df.iloc es similar a df.loc pero buscando por índice, sin poner el nombre específico del índice

In [27]:
df_desastre.iloc[:, 0:3] #Estoy pidiendo todas las filas y las columnas (índices) de la 0 a la 3

     ITEM                   FECHA                EVENTO
0       1  01/02/2023 12:00:00 AM    MOVIMIENTO EN MASA
1       2  01/02/2023 12:00:00 AM    MOVIMIENTO EN MASA
2       3  01/25/2023 12:00:00 AM               HELADAS
3       4  01/25/2023 12:00:00 AM               HELADAS
4       5  01/28/2023 12:00:00 AM     INCENDIO FORESTAL
..    ...                     ...                   ...
97     98  07/13/2023 12:00:00 AM     INCENDIO FORESTAL
98     99  07/17/2023 12:00:00 AM               EROSION
99    100  07/19/2023 12:00:00 AM     INCENDIO FORESTAL
100   101  07/22/2023 12:00:00 AM  TORMENTAS ELECTRICAS
101   102  07/25/2023 12:00:00 AM  TORMENTAS ELECTRICAS

[102 rows x 3 columns]

In [32]:
df_desastre.iloc[1,3] + ' MODIFICADA'

'FLORIDABLANCA MODIFICADA'